// [claude-code 2026-03-20] T5a: Proposals tab — active proposal card + model glossary
import { useState, useEffect, useCallback } from 'react';
import { Target, TrendingUp, TrendingDown, Loader2, AlertTriangle, Crosshair } from 'lucide-react';
import { useBackend } from '../../lib/backend';
import { ModelGlossary } from './ModelGlossary';

interface ActiveProposal {
  id: string;
  instrument: string;
  direction: 'long' | 'short' | 'flat';
  entryPrice?: number;
  stopLoss?: number;
  takeProfit?: number[];
  confidence: number;
  strategyName: string;
  rationale: string;
  createdAt: string;
}

const STRATEGY_LABELS: Record<string, string> = {
  MORNING_FLUSH: 'Morning Flush',
  LUNCH_FLUSH: 'Lunch Flush',
  POWER_HOUR_FLUSH: 'Power Hour Flush',
  VIX_FIX_22: 'VIX Fix 22',
  FORTY_FORTY_CLUB: '40/40 Club',
  MOMENTUM: 'Momentum',
  CHARGED_RIPPERS: 'Charged Rippers',
  MEAN_REVERSION: 'Mean Reversion',
  DISCRETIONARY: 'Discretionary',
  PLAYBOOK_SWEEP_RECLAIM: 'Playbook Sweep',
};

export function ProposalWidget() {
  const backend = useBackend();
  const [proposal, setProposal] = useState<ActiveProposal | null>(null);
  const [loading, setLoading] = useState(true);
  const [charting, setCharting] = useState(false);
  const [chartStatus, setChartStatus] = useState<string | null>(null);

  const fetchLatestProposal = useCallback(async () => {
    try {
      const res = await backend.autopilot.getPendingProposals();
      if (res.proposals?.length > 0) {
        const p = res.proposals[0];
        setProposal({
          id: p.id,
          instrument: p.instrument,
          direction: p.direction,
          entryPrice: p.entryPrice,
          stopLoss: p.stopLoss,
          takeProfit: p.takeProfit,
          confidence: p.confidence,
          strategyName: p.strategyName,
          rationale: p.rationale,
          createdAt: p.createdAt,
        });
      } else {
        setProposal(null);
      }
    } catch (err) {
      console.warn('[Proposals] Failed to fetch proposals:', err);
    } finally {
      setLoading(false);
    }
  }, [backend]);

  useEffect(() => {
    fetchLatestProposal();
    const interval = setInterval(fetchLatestProposal, 30000);
    return () => clearInterval(interval);
  }, [fetchLatestProposal]);

  const handleChartIt = async () => {
    if (!proposal || charting) return;
    setCharting(true);
    setChartStatus(null);
    try {
      const res = await fetch('/api/proposals/chart', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ticker: proposal.instrument,
          direction: proposal.direction,
          entry: proposal.entryPrice,
          stopLoss: proposal.stopLoss,
          takeProfit: proposal.takeProfit?.[0],
        }),
      });
      const data = await res.json();
      if (data.blackout) {
        setChartStatus('Blackout period active (8:30a-12p EST)');
      } else if (data.success) {
        setChartStatus('Charted on TopStepX');
      } else {
        setChartStatus(data.error || 'Chart failed');
      }
    } catch (err) {
      setChartStatus('Failed to connect');
    } finally {
      setCharting(false);
    }
  };

  const isLong = proposal?.direction === 'long';
  const isShort = proposal?.direction === 'short';

  return (
    <div className="h-full flex flex-col overflow-y-auto">
      {/* Header */}
      <div className="flex items-center gap-2 px-6 py-4 border-b border-zinc-800/50">
        <Target className="w-4 h-4 text-[var(--fintheon-accent)]" />
        <h2 className="text-[13px] font-bold text-[var(--fintheon-accent)] tracking-[0.15em] uppercase">
          Proposals
        </h2>
      </div>

      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6">
        {/* Active Proposal Card */}
        <div>
          <div className="text-[10px] text-zinc-500 uppercase tracking-[0.2em] font-semibold mb-2">
            Active Proposal
          </div>

          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-5 h-5 text-zinc-600 animate-spin" />
            </div>
          ) : !proposal ? (
            <div className="border border-zinc-800 rounded-lg p-6 text-center">
              <AlertTriangle className="w-5 h-5 text-zinc-600 mx-auto mb-2" />
              <div className="text-[11px] text-zinc-500">No active proposals</div>
              <div className="text-[10px] text-zinc-600 mt-1">
                Proposals are generated by the Autopilot pipeline
              </div>
            </div>
          ) : (
            <div className="border border-[var(--fintheon-accent)]/30 rounded-lg bg-[var(--fintheon-surface)] overflow-hidden">
              {/* Proposal header row */}
              <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-800/50">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-mono font-bold text-[var(--fintheon-accent)]">
                    {proposal.instrument}
                  </span>
                  <span
                    className={`text-[10px] px-1.5 py-0.5 rounded border font-semibold ${
                      isLong
                        ? 'text-green-400 bg-green-500/10 border-green-500/30'
                        : isShort
                          ? 'text-red-400 bg-red-500/10 border-red-500/30'
                          : 'text-zinc-400 bg-zinc-500/10 border-zinc-500/30'
                    }`}
                  >
                    {proposal.direction.toUpperCase()}
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  {isLong ? (
                    <TrendingUp className="w-3.5 h-3.5 text-green-400" />
                  ) : isShort ? (
                    <TrendingDown className="w-3.5 h-3.5 text-red-400" />
                  ) : null}
                  <span
                    className={`text-sm font-bold ${
                      proposal.confidence >= 70
                        ? 'text-green-400'
                        : proposal.confidence >= 50
                          ? 'text-yellow-400'
                          : 'text-red-400'
                    }`}
                  >
                    {proposal.confidence}%
                  </span>
                </div>
              </div>

              {/* Trade levels grid */}
              <div className="grid grid-cols-3 divide-x divide-zinc-800/50 border-b border-zinc-800/50">
                <div className="px-3 py-2">
                  <div className="text-[9px] text-zinc-600 uppercase">Entry</div>
                  <div className="text-[12px] font-mono text-white">
                    {proposal.entryPrice?.toFixed(2) || 'Market'}
                  </div>
                </div>
                <div className="px-3 py-2">
                  <div className="text-[9px] text-zinc-600 uppercase">Stop</div>
                  <div className="text-[12px] font-mono text-red-400">
                    {proposal.stopLoss?.toFixed(2) || 'N/A'}
                  </div>
                </div>
                <div className="px-3 py-2">
                  <div className="text-[9px] text-zinc-600 uppercase">Target</div>
                  <div className="text-[12px] font-mono text-green-400">
                    {proposal.takeProfit?.[0]?.toFixed(2) || 'N/A'}
                  </div>
                </div>
              </div>

              {/* Strategy + rationale */}
              <div className="px-4 py-3 space-y-2">
                <div className="text-[10px] text-zinc-500">
                  <span className="text-zinc-600">Strategy:</span>{' '}
                  {STRATEGY_LABELS[proposal.strategyName] || proposal.strategyName}
                </div>
                <p className="text-[10px] text-zinc-500 leading-relaxed line-clamp-3">
                  {proposal.rationale}
                </p>
              </div>

              {/* Chart It button */}
              <div className="px-4 pb-3">
                <button
                  type="button"
                  onClick={handleChartIt}
                  disabled={charting}
                  className="w-full flex items-center justify-center gap-2 py-2 rounded-md bg-[var(--fintheon-accent)]/10 border border-[var(--fintheon-accent)]/30 text-[var(--fintheon-accent)] text-[11px] font-semibold hover:bg-[var(--fintheon-accent)]/20 transition-colors disabled:opacity-50"
                >
                  {charting ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  ) : (
                    <Crosshair className="w-3.5 h-3.5" />
                  )}
                  {charting ? 'Charting...' : 'Chart It'}
                </button>
                {chartStatus && (
                  <div className="text-[9px] text-zinc-500 text-center mt-1.5">{chartStatus}</div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Model Glossary */}
        <ModelGlossary />
      </div>
    </div>
  );
}
