// Ported from https://github.com/Eronred/expo-agent-spinners (MIT) — S28-T3 2026-04-20
// Frame data for all 54 terminal-style agent spinners. Each entry pairs the frame
// list with the tick interval in ms. Every spinner is a pure string-cycle — no
// raster assets, no Lottie, no native deps.

export interface SpinnerDefinition {
  readonly frames: readonly string[];
  readonly intervalMs: number;
}

export const SPINNERS = {
  arc: {
    frames: ["◜", "◠", "◝", "◞", "◡", "◟"],
    intervalMs: 100,
  },
  arrow: {
    frames: ["←", "↖", "↑", "↗", "→", "↘", "↓", "↙"],
    intervalMs: 100,
  },
  balloon: {
    frames: [" ", ".", "o", "O", "@", "*", " "],
    intervalMs: 140,
  },
  bounce: {
    frames: ["⠁", "⠂", "⠄", "⠂"],
    intervalMs: 120,
  },
  breathe: {
    frames: ["  ●  ", " ●●● ", "●●●●●", " ●●● ", "  ●  ", "  ·  "],
    intervalMs: 160,
  },
  cascade: {
    frames: [
      "▁",
      "▂",
      "▃",
      "▄",
      "▅",
      "▆",
      "▇",
      "█",
      "▇",
      "▆",
      "▅",
      "▄",
      "▃",
      "▂",
    ],
    intervalMs: 80,
  },
  checkerboard: {
    frames: ["▌", "▀", "▐", "▄"],
    intervalMs: 100,
  },
  circleHalves: {
    frames: ["◐", "◓", "◑", "◒"],
    intervalMs: 90,
  },
  circleQuarters: {
    frames: ["◴", "◷", "◶", "◵"],
    intervalMs: 110,
  },
  clock: {
    frames: [
      "🕛",
      "🕐",
      "🕑",
      "🕒",
      "🕓",
      "🕔",
      "🕕",
      "🕖",
      "🕗",
      "🕘",
      "🕙",
      "🕚",
    ],
    intervalMs: 120,
  },
  columns: {
    frames: [
      "▏",
      "▎",
      "▍",
      "▌",
      "▋",
      "▊",
      "▉",
      "█",
      "▉",
      "▊",
      "▋",
      "▌",
      "▍",
      "▎",
    ],
    intervalMs: 80,
  },
  diagswipe: {
    frames: ["╲   ", " ╲  ", "  ╲ ", "   ╲", "   ╱", "  ╱ ", " ╱  ", "╱   "],
    intervalMs: 90,
  },
  dots: {
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
    intervalMs: 80,
  },
  dots2: {
    frames: ["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"],
    intervalMs: 80,
  },
  dots3: {
    frames: ["⠋", "⠙", "⠚", "⠞", "⠖", "⠦", "⠴", "⠲", "⠳", "⠓"],
    intervalMs: 80,
  },
  dots4: {
    frames: [
      "⠄",
      "⠆",
      "⠇",
      "⠋",
      "⠙",
      "⠸",
      "⠰",
      "⠠",
      "⠰",
      "⠸",
      "⠙",
      "⠋",
      "⠇",
      "⠆",
    ],
    intervalMs: 80,
  },
  dots5: {
    frames: [
      "⠋",
      "⠙",
      "⠚",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠲",
      "⠴",
      "⠦",
      "⠖",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠓",
      "⠋",
    ],
    intervalMs: 80,
  },
  dots6: {
    frames: [
      "⠁",
      "⠉",
      "⠙",
      "⠚",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠲",
      "⠴",
      "⠤",
      "⠄",
      "⠄",
      "⠤",
      "⠴",
      "⠲",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠚",
      "⠙",
      "⠉",
      "⠁",
    ],
    intervalMs: 80,
  },
  dots7: {
    frames: [
      "⠈",
      "⠉",
      "⠋",
      "⠓",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠖",
      "⠦",
      "⠤",
      "⠠",
      "⠠",
      "⠤",
      "⠦",
      "⠖",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠓",
      "⠋",
      "⠉",
      "⠈",
    ],
    intervalMs: 80,
  },
  dots8: {
    frames: [
      "⠁",
      "⠁",
      "⠉",
      "⠙",
      "⠚",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠲",
      "⠴",
      "⠤",
      "⠄",
      "⠄",
      "⠤",
      "⠠",
      "⠠",
      "⠤",
      "⠦",
      "⠖",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠓",
      "⠋",
      "⠉",
      "⠈",
      "⠈",
    ],
    intervalMs: 80,
  },
  dots9: {
    frames: ["⢹", "⢺", "⢼", "⣸", "⣇", "⡧", "⡗", "⡏"],
    intervalMs: 80,
  },
  dots10: {
    frames: ["⢄", "⢂", "⢁", "⡁", "⡈", "⡐", "⡠"],
    intervalMs: 80,
  },
  dots11: {
    frames: ["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"],
    intervalMs: 100,
  },
  dots12: {
    frames: [
      "⢀⠀",
      "⡀⠀",
      "⠄⠀",
      "⢂⠀",
      "⡂⠀",
      "⠅⠀",
      "⢃⠀",
      "⡃⠀",
      "⠍⠀",
      "⢋⠀",
      "⡋⠀",
      "⠍⠁",
      "⢋⠁",
      "⡋⠁",
      "⠍⠉",
      "⠋⠉",
      "⠋⠉",
      "⠉⠙",
      "⠉⠙",
      "⠉⠩",
      "⠈⢙",
      "⠈⡙",
      "⢈⠩",
      "⡀⢙",
      "⠄⡙",
      "⢂⠩",
      "⡂⢘",
      "⠅⡘",
      "⢃⠨",
      "⡃⢐",
      "⠍⡐",
      "⢋⠠",
      "⡋⢀",
      "⠍⡁",
      "⢋⠁",
      "⡋⠁",
      "⠍⠉",
      "⠋⠉",
      "⠋⠉",
      "⠉⠙",
      "⠉⠙",
      "⠉⠩",
      "⠈⢙",
      "⠈⡙",
      "⠈⠩",
      "⠀⢙",
      "⠀⡙",
      "⠀⠩",
      "⠀⢘",
      "⠀⡘",
      "⠀⠨",
      "⠀⢐",
      "⠀⡐",
      "⠀⠠",
      "⠀⢀",
      "⠀⡀",
    ],
    intervalMs: 80,
  },
  dots13: {
    frames: ["⣼", "⣹", "⢻", "⠿", "⡟", "⣏", "⣧", "⣶"],
    intervalMs: 80,
  },
  dots14: {
    frames: [
      "⠉⠉",
      "⠈⠙",
      "⠀⠹",
      "⠀⢸",
      "⠀⣰",
      "⢀⣠",
      "⣀⣀",
      "⣄⡀",
      "⣆⠀",
      "⡇⠀",
      "⠏⠀",
      "⠋⠁",
    ],
    intervalMs: 80,
  },
  doubleArrow: {
    frames: ["»»", "»≫", "≫»", "»»"],
    intervalMs: 120,
  },
  dqpb: {
    frames: ["d", "q", "p", "b"],
    intervalMs: 100,
  },
  earth: {
    frames: ["🌍", "🌎", "🌏"],
    intervalMs: 180,
  },
  fillsweep: {
    frames: ["▱▱▱▱▱", "▰▱▱▱▱", "▰▰▱▱▱", "▰▰▰▱▱", "▰▰▰▰▱", "▰▰▰▰▰"],
    intervalMs: 90,
  },
  growHorizontal: {
    frames: ["▏", "▎", "▍", "▌", "▋", "▊", "▉", "▊", "▋", "▌", "▍", "▎"],
    intervalMs: 120,
  },
  growVertical: {
    frames: ["▁", "▃", "▄", "▅", "▆", "▇", "▆", "▅", "▄", "▃"],
    intervalMs: 120,
  },
  hearts: {
    frames: ["💛", "💙", "💜", "💚", "❤️"],
    intervalMs: 100,
  },
  helix: {
    frames: ["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"],
    intervalMs: 110,
  },
  moon: {
    frames: ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"],
    intervalMs: 160,
  },
  noise: {
    frames: ["▓", "▒", "░"],
    intervalMs: 100,
  },
  orbit: {
    frames: [
      "●    ",
      " ●   ",
      "  ●  ",
      "   ● ",
      "    ●",
      "   ● ",
      "  ●  ",
      " ●   ",
    ],
    intervalMs: 100,
  },
  point: {
    frames: ["∙∙∙", "●∙∙", "∙●∙", "∙∙●", "∙∙∙"],
    intervalMs: 125,
  },
  pulse: {
    frames: ["·", "•", "●", "•"],
    intervalMs: 140,
  },
  rain: {
    frames: [
      "│ │ │ │",
      "╷ │ │ │",
      "│ ╷ │ │",
      "│ │ ╷ │",
      "│ │ │ ╷",
      "╵ │ │ │",
      "│ ╵ │ │",
      "│ │ ╵ │",
      "│ │ │ ╵",
    ],
    intervalMs: 110,
  },
  rollingLine: {
    frames: ["-", "\\", "|", "/"],
    intervalMs: 120,
  },
  sand: {
    frames: ["⠁", "⠃", "⠇", "⡇", "⣇", "⣧", "⣷", "⣿", "⣾", "⣶", "⣆", "⣀"],
    intervalMs: 120,
  },
  scan: {
    frames: [
      "[=    ]",
      "[==   ]",
      "[===  ]",
      "[==== ]",
      "[=====]",
      "[ ====]",
      "[  ===]",
      "[   ==]",
      "[    =]",
      "[     ]",
    ],
    intervalMs: 90,
  },
  simpleDots: {
    frames: [".  ", ".. ", "...", "   "],
    intervalMs: 400,
  },
  simpleDotsScrolling: {
    frames: [".  ", ".. ", "...", " ..", "  .", "   "],
    intervalMs: 200,
  },
  snake: {
    frames: [
      "⠈⠁",
      "⠈⠑",
      "⠈⠱",
      "⠈⡱",
      "⢀⡱",
      "⢄⡱",
      "⢄⡱",
      "⢆⡱",
      "⢎⡱",
      "⢎⡰",
      "⢎⡠",
      "⢎⡀",
      "⢎⠀",
      "⠎⠀",
      "⠊⠀",
    ],
    intervalMs: 100,
  },
  sparkle: {
    frames: ["✦", "✧", "✫", "✬", "✭", "✮", "✯", "✰"],
    intervalMs: 110,
  },
  speaker: {
    frames: ["🔈", "🔉", "🔊", "🔉"],
    intervalMs: 160,
  },
  squareCorners: {
    frames: ["◰", "◳", "◲", "◱"],
    intervalMs: 180,
  },
  toggle: {
    frames: ["⊶", "⊷"],
    intervalMs: 250,
  },
  triangle: {
    frames: ["◢", "◣", "◤", "◥"],
    intervalMs: 50,
  },
  wave: {
    frames: [
      "▁▂▃▄▅▆▇",
      "▂▃▄▅▆▇▆",
      "▃▄▅▆▇▆▅",
      "▄▅▆▇▆▅▄",
      "▅▆▇▆▅▄▃",
      "▆▇▆▅▄▃▂",
      "▇▆▅▄▃▂▁",
      "▆▅▄▃▂▁▂",
      "▅▄▃▂▁▂▃",
      "▄▃▂▁▂▃▄",
      "▃▂▁▂▃▄▅",
      "▂▁▂▃▄▅▆",
    ],
    intervalMs: 90,
  },
  waveRows: {
    frames: [
      "▂▃▄▅▆▇",
      "▃▄▅▆▇▆",
      "▄▅▆▇▆▅",
      "▅▆▇▆▅▄",
      "▆▇▆▅▄▃",
      "▇▆▅▄▃▂",
      "▆▅▄▃▂▁",
    ],
    intervalMs: 90,
  },
  weather: {
    frames: ["☀️", "☀️", "⛅", "☁️", "🌧️", "⛈️", "🌧️", "☁️", "⛅"],
    intervalMs: 180,
  },
} as const satisfies Record<string, SpinnerDefinition>;

export type SpinnerKey = keyof typeof SPINNERS;
