// [claude-code 2026-03-22] Source of Truth fusion — full 14 commandments with metadata
import type { Commandment } from './types';

export const COMMANDMENTS: Commandment[] = [
  {
    number: 1,
    text: 'There is always another trade',
    fullText: 'Anti-FOMO anchor. The market offers infinite opportunities. Never chase a missed entry — the next setup is always coming.',
    blockLevel: 'soft',
    coreLessons: ['Anti-FOMO', 'Anti-revenge trading', 'Patience is edge'],
    agentUsage: {
      Harper: 'Cites after missed entries or during loss streaks',
      Feucht: 'References when rejecting low-conviction setups',
    },
    relatedCommandments: [13],
  },
  {
    number: 2,
    text: 'The markets will always trade',
    fullText: 'Patience anchor. No single session defines you. Markets don\'t close forever.',
    blockLevel: 'guidance',
    coreLessons: ['No session defines you', 'Markets are infinite', 'Patience over desperation'],
    agentUsage: {
      Harper: 'Uses when TP is desperate or under financial pressure',
      All: 'Reinforces during dead calendar days',
    },
    relatedCommandments: [],
  },
  {
    number: 3,
    text: 'No shot in the dark trades',
    fullText: 'Every trade needs a thesis backed by the playbook. If confluence score is below threshold, the trade is blocked.',
    blockLevel: 'hard',
    coreLessons: ['Conviction required', 'Thesis before entry', 'No guessing'],
    agentUsage: {
      Feucht: 'Pre-trade checklist gate — blocks if confluence < threshold',
      Harper: 'Validates conviction level before approval',
    },
    relatedCommandments: [8, 10],
  },
  {
    number: 4,
    text: 'You can\'t go broke taking profits',
    fullText: 'PDPT exists for a reason ($1,550). Take the money. Don\'t hold past target hoping for more.',
    blockLevel: 'soft',
    coreLessons: ['PDPT discipline', 'Profit management', 'Greed kills'],
    agentUsage: {
      Feucht: 'Flags when holding past PDPT $1,550 target',
      Harper: 'Profit management reminder',
    },
    relatedCommandments: [9],
  },
  {
    number: 5,
    text: 'Know what tape you\'re trading',
    fullText: 'Regime detection must happen before setup selection. Wrong model on wrong tape = losses.',
    blockLevel: 'soft',
    coreLessons: ['Regime detection first', 'Match model to tape', 'No blind entries'],
    agentUsage: {
      Feucht: 'Must identify tape type before recommending setups',
      Oracle: 'Identifies regime (trending/choppy, efficient/inefficient)',
    },
    relatedCommandments: [3],
  },
  {
    number: 6,
    text: 'Never make back losses the same way you lost them',
    fullText: 'Anti-revenge trading. The #1 weakness. If you lost on NQ long, don\'t immediately re-enter NQ long.',
    blockLevel: 'soft',
    coreLessons: ['Anti-revenge', 'Switch instrument or direction', 'Cool-down period'],
    agentUsage: {
      Harper: 'Flags re-entry on same instrument/direction after loss',
      PsychAssist: 'Primary tilt detection vector',
    },
    relatedCommandments: [1, 7, 13],
  },
  {
    number: 7,
    text: 'No doubling down on losers',
    fullText: 'Conviction is not stubbornness. If the position is losing, cut it. Do NOT add to it. Reassess from scratch.',
    blockLevel: 'hard',
    coreLessons: ['Cut losers immediately', 'Conviction != stubbornness', 'Fresh reassessment'],
    agentUsage: {
      Feucht: 'Blocks adding to losing positions automatically',
      'Risk Manager': 'Rejects proposals that increase exposure on losers',
    },
    relatedCommandments: [6, 12],
  },
  {
    number: 8,
    text: 'Good traders buy from good prices',
    fullText: '"Good traders buy from good prices, and a good trade is a hard trade." Entry at the last line of defense — Fibonacci level where price must hold or thesis is invalidated.',
    blockLevel: 'soft',
    coreLessons: ['Entry quality is everything', 'Last line of defense', 'Min R:R 2:1'],
    agentUsage: {
      Feucht: 'Fibonacci entry quality gate, validates key level',
      Harper: 'Validates entry is at a key level, not chasing',
    },
    relatedCommandments: [3, 12],
    mentorSource: 'Dr. David Paul',
  },
  {
    number: 9,
    text: 'Good things happen to traders who wait',
    fullText: 'Don\'t force trades. The setup comes to you. Session discipline — if there\'s no setup, there\'s no trade.',
    blockLevel: 'soft',
    coreLessons: ['Don\'t force it', 'Setup comes to you', 'Patience pays'],
    agentUsage: {
      All: 'Reinforced during slow/quiet markets',
      Harper: 'Session discipline reminder',
    },
    relatedCommandments: [2, 11],
  },
  {
    number: 10,
    text: 'Only fight for things worth fighting for',
    fullText: 'Not every move deserves your capital. If the setup has degraded, walk away. Protect capital for the next high-conviction play.',
    blockLevel: 'soft',
    coreLessons: ['Thesis validation before entry', 'Walk away from degraded setups', 'Capital preservation'],
    agentUsage: {
      Harper: 'Recommends walking away if setup has degraded',
      Feucht: 'Thesis re-validation before execution',
    },
    relatedCommandments: [3, 11],
  },
  {
    number: 11,
    text: 'Some days there is nothing to do',
    fullText: 'Action bias is the enemy. On dead calendars with no catalyst, the right trade is no trade.',
    blockLevel: 'soft',
    coreLessons: ['Action bias kills', 'No catalyst = no trade', 'Sitting out IS a position'],
    agentUsage: {
      Harper: 'Actively recommends sitting out on dead calendars',
      All: 'Daily no-trade recommendation when no catalyst present',
    },
    relatedCommandments: [2, 9],
  },
  {
    number: 12,
    text: 'Be right or be right out',
    fullText: 'Stop-loss is non-negotiable. Quick cuts, no hoping, no praying. Every trade must have a defined stop before entry.',
    blockLevel: 'hard',
    coreLessons: ['Stop-loss mandatory', 'Quick cuts', 'No hoping or praying'],
    agentUsage: {
      Feucht: 'Stop-loss enforcement on every trade',
      'Risk Manager': 'Rejects proposals without a defined stop-loss level',
    },
    relatedCommandments: [7, 8],
  },
  {
    number: 13,
    text: 'There is always another trade',
    fullText: 'Bookend with Commandment 1. The repetition is intentional. This is the last thought before every forced or marginal trade.',
    blockLevel: 'soft',
    coreLessons: ['Circuit breaker reminder', 'End-of-session anchor', 'Walk away clean'],
    agentUsage: {
      Harper: 'Circuit breaker reminder at end of session',
      All: 'Final check before any forced or marginal trade',
    },
    relatedCommandments: [1],
  },
  {
    number: 14,
    text: 'The morning routine is non-negotiable',
    fullText: 'Skip the 30-45 min calibration and you\'re trading blind. The routine IS the edge. No routine, no trades.',
    blockLevel: 'hard',
    coreLessons: ['Routine is the edge', 'No routine = no trading', 'Calibration before execution'],
    agentUsage: {
      Harper: 'Checks morning routine completion before approving first trade',
      PsychAssist: 'Gates trading until routine is verified complete',
    },
    relatedCommandments: [3],
  },
];
